/**
 * Subprocess lifecycle for the bundled mini-swe-agent. Runs use its lightweight
 * embedded entry point when available; custom/older `mini` launchers keep using
 * the public CLI so overriding the integration never hard-fails.
 */

import { appendFileSync, closeSync, existsSync, openSync, readSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { miniBin, createSessionDir, type SessionPaths } from "../config";
import { gitIdentityEnv } from "../gitIdentity";
import { resolveCommand, resolvePython } from "../helpers";

export interface TaskSpec {
  task: string;
  model?: string;
  specs?: string[];
  cwd?: string;
  /** Continue an earlier conversation: `mini --resume <file>` with its raw messages. */
  resumePath?: string;
  /** Extra environment for the run (e.g. BYOK provider keys). */
  env?: Record<string, string>;
  /** `/compact` without a live run: compact `resumePath` and wait (integrated runner only). */
  compactOnly?: boolean;
  /**
   * Keep the control channel (default). With it, the agent holds at exit waiting for a
   * follow-up; headless runs (`mini-tui -p`) turn it off so the process ends with the turn.
   */
  control?: boolean;
}

export type RunnerKind = "embedded" | "cli" | "argv" | "rust";
const TUI_RUNNER_MODULE = "minisweagent.run.tui";
let runnerSupport: RunnerKind | undefined;

/** Build the public CLI argv for a run (exported for tests and fallback). */
export function buildMiniArgs(spec: TaskSpec, session: SessionPaths): string[] {
  const args = [miniBin(), "-y", "--exit-immediately", "-o", session.trajPath];
  if (spec.resumePath) args.push("--resume", spec.resumePath);
  if (spec.model) args.push("-m", spec.model);
  for (const configSpec of spec.specs ?? []) args.push("-c", configSpec);
  args.push("-t", spec.task);
  return args;
}

function buildRunnerArgs(spec: TaskSpec, session: SessionPaths): string[] {
  const args = ["-y", "--exit-immediately", "-o", session.trajPath];
  if (spec.resumePath) args.push("--resume", spec.resumePath);
  if (spec.model) args.push("-m", spec.model);
  for (const configSpec of spec.specs ?? []) args.push("-c", configSpec);
  if (spec.compactOnly) args.push("--compact-only");
  else args.push("-t", spec.task);
  return args;
}

/** Whether the selected runner can take `--compact-only` (the plain `mini` CLI cannot). */
export function runnerSupportsCompactOnly(): boolean {
  return selectRunner() !== "cli";
}

/**
 * The Rust port of the agent (`agent-rs/`): same command line, trajectory, journal and control
 * file as the Python runner, as one self-contained binary. `MINITUI_AGENT_BIN` points at the
 * binary; otherwise the repo's release build, then the installed copy, then PATH.
 */
export function rustAgentBin(env: NodeJS.ProcessEnv = process.env): string | undefined {
  if (env.MINITUI_AGENT_BIN) return existsSync(env.MINITUI_AGENT_BIN) ? env.MINITUI_AGENT_BIN : undefined;
  const built = new URL("../../agent-rs/target/release/mini-agent-rs", import.meta.url).pathname;
  if (existsSync(built)) return built;
  const installed = join(homedir(), ".local", "lib", "mini-tui", "mini-agent-rs");
  if (existsSync(installed)) return installed;
  const onPath = resolveCommand("mini-agent-rs", env);
  return onPath.includes("/") ? onPath : undefined;
}

/**
 * The Rust agent is the default whenever its binary is there: the TUI, `mini-tui -p` and the web
 * app all use it. `MINITUI_AGENT=python` keeps the Python agent; `MINITUI_AGENT=rust` insists on
 * Rust (and says so when the binary is missing). Returns the binary to run, or undefined for Python.
 */
export function rustAgent(env: NodeJS.ProcessEnv = process.env): string | undefined {
  if (env.MINITUI_AGENT === "python") return undefined;
  return rustAgentBin(env);
}

/** Resolve a console script beside a custom `mini` launcher, if one exists. */
function resolveTuiRunner(env: NodeJS.ProcessEnv = process.env): string {
  const launcher = resolveCommand(miniBin(), env);
  if (!launcher.includes("/")) return "";
  const dir = launcher.slice(0, launcher.lastIndexOf("/"));
  return `${dir}/mini-swe-agent-tui`;
}

export function detectRunner(): RunnerKind {
  // `MINITUI_EMBEDDED_AGENT=0` means "run exactly the `mini` launcher I gave you" (custom wrappers,
  // test stubs): it wins over the agent choice.
  if (process.env.MINITUI_EMBEDDED_AGENT !== "0") {
    if (rustAgent()) return "rust";
    // Asked for by name but missing: say so once and keep working with the Python agent.
    if (process.env.MINITUI_AGENT === "rust") console.error("MINITUI_AGENT=rust but no mini-agent-rs binary was found (build agent-rs/ or set MINITUI_AGENT_BIN); using the Python agent");
  }
  if (process.env.MINITUI_EMBEDDED_AGENT === "0") return "cli";
  // Prefer the console script: it is generated by the bundled pyproject and
  // costs no capability-probe process. Older editable installs may expose only
  // the module, so retain the import fallback for them.
  const script = resolveTuiRunner();
  if (script && existsSync(script)) {
    const scriptCheck = Bun.spawnSync({
      cmd: [resolvePython(), script, "--help"],
      stdin: "ignore",
      stdout: "ignore",
      stderr: "ignore",
      env: { ...process.env, MSWEA_SILENT_STARTUP: "1", MSWEA_CONTROL_FILE: "" },
    });
    if (scriptCheck.exitCode === 0) return "argv";
  }
  const env = { ...process.env, MSWEA_SILENT_STARTUP: "1", MSWEA_CONTROL_FILE: "" };
  const moduleCheck = Bun.spawnSync({
    cmd: [resolvePython(), "-c", `import ${TUI_RUNNER_MODULE}`],
    stdin: "ignore",
    stdout: "ignore",
    stderr: "ignore",
    env,
  });
  return moduleCheck.exitCode === 0 ? "embedded" : "cli";
}

function selectRunner(): RunnerKind {
  if (runnerSupport === undefined) runnerSupport = detectRunner();
  return runnerSupport;
}

/** Reset the process-local entry-point probe (test/embedding hook). */
export function resetRunnerSupport(): void {
  runnerSupport = undefined;
}

/** Force a runner for a test or embedding process without spawning a probe. */
export function setRunnerSupport(kind: RunnerKind | undefined): void {
  runnerSupport = kind;
}

/** Build the argv for an integrated runner; exported for deterministic tests. */
export function buildRunnerCommand(spec: TaskSpec, session: SessionPaths, kind: RunnerKind = "embedded"): string[] {
  if (kind === "rust") return [rustAgentBin() ?? "mini-agent-rs", ...buildRunnerArgs(spec, session)];
  if (kind === "embedded") return [resolvePython(), "-m", TUI_RUNNER_MODULE, ...buildRunnerArgs(spec, session)];
  if (kind === "argv") {
    const launcher = resolveTuiRunner();
    return launcher ? [resolvePython(), launcher, ...buildRunnerArgs(spec, session)] : [miniBin(), ...buildRunnerArgs(spec, session)];
  }
  return buildMiniArgs(spec, session);
}

export interface MiniRun {
  session: SessionPaths;
  pid?: number;
  cmd: string[];
  /** Which integrated launch path was selected. */
  runner: RunnerKind;
  /** Resolves with the exit code (null when killed by a signal). */
  exited: Promise<number | null>;
  kill(): void;
  /** Interrupt the run in flight (SIGINT, then SIGTERM if needed). */
  interrupt(): void;
  /** Ask the running agent to switch model from its next step (control file). */
  switchModel(model: string): void;
  /** Send a follow-up prompt that continues the same conversation (control file). */
  sendUserMessage(text: string): void;
  /** Ask the running agent to compact its context before the next model call (`/compact`). */
  requestCompact(): void;
}

/** The YAML configs shipped with the bundled Python agent; the Rust agent reads the same ones. */
const BUNDLED_CONFIG_DIR = new URL("../../agent/src/minisweagent/config", import.meta.url).pathname;

/** Build the isolated environment shared by integrated and fallback runs. */
export function buildRunEnv(
  session: SessionPaths,
  extra: Record<string, string> = {},
  control = true,
): Record<string, string> {
  return {
    ...process.env,
    // Commits made by the agent are authored by the user's gh/git identity, never "claude".
    ...gitIdentityEnv({ ...process.env, ...extra }),
    ...extra,
    // The Rust binary may live outside this checkout (~/.local/lib/mini-tui): point it at the YAML
    // configs shipped with the bundled agent, unless the caller already chose a directory.
    ...(process.env.MINI_AGENT_CONFIG_DIR || extra.MINI_AGENT_CONFIG_DIR ? {} : { MINI_AGENT_CONFIG_DIR: BUNDLED_CONFIG_DIR }),
    // Empty = no control channel: the agent finishes its turn and exits (headless runs).
    MSWEA_CONTROL_FILE: control ? session.controlPath : "",
    MSWEA_SILENT_STARTUP: "1",
  } as Record<string, string>;
}

export function spawnMini(spec: TaskSpec): MiniRun {
  const session = createSessionDir(spec.task);
  const runner = selectRunner();
  const cmd = buildRunnerCommand(spec, session, runner);
  // A run must never inherit the control file of a previous/parallel TUI
  // process; each session owns one line protocol and one agent.
  const env = buildRunEnv(session, spec.env, spec.control !== false);
  const logFd = openSync(session.logPath, "a");
  const proc = Bun.spawn({ cmd, cwd: spec.cwd ?? process.cwd(), stdin: "ignore", stdout: logFd, stderr: logFd, env });
  closeSync(logFd);
  writeFileSync(session.pidPath, `${proc.pid}\n`);

  let exiting = false;
  const onExit = () => {
    try {
      proc.kill("SIGTERM");
    } catch {
      // already gone
    }
  };
  process.once("exit", onExit);
  const exited = proc.exited.then((code) => {
    process.removeListener("exit", onExit);
    return code as number | null;
  });

  return {
    session,
    pid: proc.pid,
    cmd,
    runner,
    exited,
    interrupt() {
      try {
        proc.kill("SIGINT");
      } catch {
        return; // already gone
      }
      setTimeout(() => {
        try {
          proc.kill("SIGTERM");
        } catch {
          // already gone
        }
      }, 2000).unref?.();
    },
    kill() {
      if (exiting) return;
      exiting = true;
      try {
        proc.kill("SIGTERM");
      } catch {
        // already gone
      }
      setTimeout(() => {
        try {
          proc.kill("SIGKILL");
        } catch {
          // already gone
        }
      }, 5000).unref?.();
    },
    switchModel(model: string) {
      // The agent reads MSWEA_CONTROL_FILE before each model call (last `MODEL` line wins).
      appendFileSync(session.controlPath, `MODEL ${model}\n`);
    },
    requestCompact() {
      appendFileSync(session.controlPath, "COMPACT\n");
    },
    sendUserMessage(text: string) {
      // JSON-quoted so multi-line prompts survive the line-based protocol.
      appendFileSync(session.controlPath, `MESSAGE ${JSON.stringify(text)}\n`);
    },
  };
}

/** Tail of the raw `mini` output, for error banners (last 64 KB — the log can be huge). */
export function tailLog(logPath: string, lines = 12): string {
  try {
    const size = statSync(logPath).size;
    const length = Math.min(size, 64 * 1024);
    const buffer = Buffer.alloc(length);
    const fd = openSync(logPath, "r");
    try {
      readSync(fd, buffer, 0, length, Math.max(0, size - length));
    } finally {
      closeSync(fd);
    }
    return buffer.toString("utf8").split("\n").slice(-lines).join("\n").trim();
  } catch {
    return "";
  }
}
