// Generated by agent-rs/scripts/gen_go_catalog.py from agent/src/minisweagent/models/opencode_go_model.py.
// Do not edit by hand: regenerate when the Python table changes.

pub struct GoModel {
    pub id: &'static str,
    pub endpoint: &'static str,
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
    pub tier_threshold: i64,
    pub tier_input: f64,
    pub tier_output: f64,
    pub tier_cache_read: f64,
    pub tier_cache_write: f64,
    pub context_window: i64,
}

pub const GO_MODELS: &[GoModel] = &[
    GoModel { id: "grok-4.7", endpoint: "responses", input: 2.0, output: 6.0, cache_read: 0.5, cache_write: 0.0, tier_threshold: 200000, tier_input: 4.0, tier_output: 12.0, tier_cache_read: 1.0, tier_cache_write: 0.0, context_window: 500000 },
    GoModel { id: "grok-4.6", endpoint: "responses", input: 2.0, output: 6.0, cache_read: 0.5, cache_write: 0.0, tier_threshold: 200000, tier_input: 4.0, tier_output: 12.0, tier_cache_read: 1.0, tier_cache_write: 0.0, context_window: 500000 },
    GoModel { id: "gpt-5.6-luna", endpoint: "responses", input: 0.2, output: 1.2, cache_read: 0.02, cache_write: 0.25, tier_threshold: 272000, tier_input: 0.4, tier_output: 1.8, tier_cache_read: 0.04, tier_cache_write: 0.5, context_window: 1050000 },
    GoModel { id: "glm-5.3-flash", endpoint: "chat", input: 0.15, output: 0.5, cache_read: 0.03, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "glm-5.3", endpoint: "chat", input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "glm-5.2", endpoint: "chat", input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "glm-5.1", endpoint: "chat", input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 202752 },
    GoModel { id: "kimi-k3", endpoint: "chat", input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1048576 },
    GoModel { id: "kimi-k2.7-code", endpoint: "chat", input: 0.95, output: 4.0, cache_read: 0.19, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 262144 },
    GoModel { id: "kimi-k2.6", endpoint: "chat", input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 262144 },
    GoModel { id: "longcat-2.0", endpoint: "chat", input: 0.3, output: 1.2, cache_read: 0.006, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "deepseek-v4.1-flash", endpoint: "chat", input: 0.15, output: 0.6, cache_read: 0.003, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "deepseek-v4-pro", endpoint: "chat", input: 0.66, output: 1.98, cache_read: 0.022, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "deepseek-v4-flash", endpoint: "chat", input: 0.15, output: 0.6, cache_read: 0.003, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "deepseek-v4-flash-vision-exp", endpoint: "chat", input: 0.15, output: 0.6, cache_read: 0.003, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "mimo-v2.6-flash", endpoint: "chat", input: 0.14, output: 0.28, cache_read: 0.0028, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "mimo-v2.6-pro", endpoint: "chat", input: 0.435, output: 0.87, cache_read: 0.003625, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1048576 },
    GoModel { id: "mimo-v2.5", endpoint: "chat", input: 0.14, output: 0.28, cache_read: 0.0028, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "mimo-v2.5-pro", endpoint: "chat", input: 0.435, output: 0.87, cache_read: 0.003625, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1048576 },
    GoModel { id: "minimax-m3", endpoint: "messages", input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "minimax-m2.7", endpoint: "messages", input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.375, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 204800 },
    GoModel { id: "minimax-m2.5", endpoint: "messages", input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.375, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 204800 },
    GoModel { id: "muse-spark-1.3-contributor", endpoint: "responses", input: 0.1, output: 0.2, cache_read: 0.002, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1048576 },
    GoModel { id: "muse-spark-1.2-contributor", endpoint: "responses", input: 0.1, output: 0.2, cache_read: 0.002, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1048576 },
    GoModel { id: "qwen3.8-max", endpoint: "messages", input: 2.0, output: 6.0, cache_read: 0.25, cache_write: 2.5, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "qwen3.8-flash", endpoint: "messages", input: 0.15, output: 0.47, cache_read: 0.016, cache_write: 0.2, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "qwen3.7-max", endpoint: "messages", input: 2.5, output: 7.5, cache_read: 0.5, cache_write: 3.125, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1000000 },
    GoModel { id: "qwen3.7-plus", endpoint: "messages", input: 0.4, output: 1.6, cache_read: 0.04, cache_write: 0.5, tier_threshold: 256000, tier_input: 1.2, tier_output: 4.8, tier_cache_read: 0.12, tier_cache_write: 1.5, context_window: 1000000 },
    GoModel { id: "qwen3.6-plus", endpoint: "messages", input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.625, tier_threshold: 256000, tier_input: 2.0, tier_output: 6.0, tier_cache_read: 0.2, tier_cache_write: 2.5, context_window: 1000000 },
    GoModel { id: "hy4-preview", endpoint: "chat", input: 0.834, output: 2.501, cache_read: 0.042, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 1024000 },
    GoModel { id: "hy3", endpoint: "chat", input: 0.14, output: 0.58, cache_read: 0.035, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 256000 },
    GoModel { id: "space-bunny-free", endpoint: "chat", input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0, tier_threshold: 0, tier_input: 0.0, tier_output: 0.0, tier_cache_read: 0.0, tier_cache_write: 0.0, context_window: 500000 },
];

pub const REASONING_CONTENT_MODELS: &[&str] = &["deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "deepseek-v4-pro", "deepseek-v4.1-flash", "kimi-k2.6", "qwen3.6-plus"];
pub const NO_REASONING_EFFORT_MODELS: &[&str] = &["kimi-k2.6"];
