"""Regenerate src/models/go_catalog.rs from the Python agent's OpenCode Go table.

    python3 agent-rs/scripts/gen_go_catalog.py   (from the repo root, with the agent importable)
"""
import os, sys
os.environ.setdefault("MSWEA_SILENT_STARTUP", "1")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "agent", "src"))
from minisweagent.models import opencode_go_model as go

def f(x):
    return repr(float(x))

rows = []
for m in go.OPENCODE_GO_MODELS:
    rows.append(
        f'    GoModel {{ id: {m.id.lower()!r}, endpoint: {m.endpoint!r}, input: {f(m.input)}, output: {f(m.output)}, '
        f'cache_read: {f(m.cache_read)}, cache_write: {f(m.cache_write)}, tier_threshold: {int(m.tier_threshold or 0)}, '
        f'tier_input: {f(m.tier_input)}, tier_output: {f(m.tier_output)}, tier_cache_read: {f(m.tier_cache_read)}, '
        f'tier_cache_write: {f(m.tier_cache_write)}, context_window: {int(m.context_window)} }},'.replace("'", '"')
    )
out = "// Generated by agent-rs/scripts/gen_go_catalog.py from agent/src/minisweagent/models/opencode_go_model.py.\n"
out += "// Do not edit by hand: regenerate when the Python table changes.\n\n"
out += "pub struct GoModel {\n    pub id: &'static str,\n    pub endpoint: &'static str,\n    pub input: f64,\n    pub output: f64,\n    pub cache_read: f64,\n    pub cache_write: f64,\n    pub tier_threshold: i64,\n    pub tier_input: f64,\n    pub tier_output: f64,\n    pub tier_cache_read: f64,\n    pub tier_cache_write: f64,\n    pub context_window: i64,\n}\n\n"
out += "pub const GO_MODELS: &[GoModel] = &[\n" + "\n".join(rows) + "\n];\n\n"
out += "pub const REASONING_CONTENT_MODELS: &[&str] = &[" + ", ".join(f'"{x}"' for x in sorted(go.REASONING_CONTENT_MODELS)) + "];\n"
out += "pub const NO_REASONING_EFFORT_MODELS: &[&str] = &[" + ", ".join(f'"{x}"' for x in sorted(go.NO_REASONING_EFFORT_MODELS)) + "];\n"
path = os.path.join(os.path.dirname(__file__), "..", "src", "models", "go_catalog.rs")
open(path, "w").write(out)
print(f"{len(rows)} models -> {os.path.relpath(path)}")
